[tool.git-mirror.github]
host_type = "github"
host_url = "https://api.github.com"
user_name = "matthewdeanmartin"
target_dir = "f:/github/"
include_private = false

[tool.git-mirror.github.repos]

[tool.git-mirror.gitlab]
host_type = "gitlab"
host_url = "https://gitlab.com"
user_name = "matthewdeanmartin"
target_dir = "f:/gitlab/"
include_private = true
include_forks = false

[tool.git-mirror.selfhosted]
host_type = "gitlab"
host_url = "http://git.example.com"
user_name = "mmartin"
target_dir = "e:/self/"
include_private = true
include_forks = false


[tool.git-mirror.gitlab.repos]
